spring.application.name=smartcart

spring.datasource.url=jdbc:postgresql://localhost:5432/smartcart
spring.datasource.username=REPLACE_ME
spring.datasource.password=REPLACE_ME
spring.datasource.driver-class-name=org.postgresql.Driver

access.secret=REPLACE_ME
refresh.secret=REPLACE_ME

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=REPLACE_ME
spring.mail.password=REPLACE_ME
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.security.oauth2.client.registration.google.client-id=REPLACE_ME
spring.security.oauth2.client.registration.google.client-secret=REPLACE_ME


